site_name: SBAC-PAD 2026

theme:
  name: material
  palette:
    primary: custom  #white
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.path
    #- navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
    - toc.follow
    #- toc.integrate 
    - navigation.instant
    - navigation.indexes

  custom_dir: overrides

plugins:
  - search:
      enabled: false
  - glightbox
  - blog

watch:
  - mkdocs.yml
  - docs/
  - overrides/

nav:
  - Home: index.md
  - News: 
    - blog/index.md
  - Submissions:
      - Call for Papers: submissions/call-for-papers.md
      - Call for Workshops Proposals: submissions/call-for-workshops-proposals.md
      - Call for Tutorials Proposals: submissions/call-for-tutorials.md
      - Important Dates: submissions/important-dates.md
  - Committes:
      - Organizing Committee: committees/organizing-committee.md
      - Program Committee: committees/program-committee.md
  - Conference:
      - Keynotes: conference/keynotes.md
      - Registration: conference/registration.md
      - Sponsors: conference/sponsors.md
      - Program: conference/program.md
      - Co-Located Events: conference/co-located.md
  - Attending: 
      - Venue: attending/venue.md
      - Travel Information: attending/travel-information.md
      - Visa Information: attending/visa-information.md
      - Things to Do: attending/things-to-do.md
  - Past Editions: https://www2.sbc.org.br/ce-acpad/sbac-pad/

markdown_extensions:
  - neoteroi.timeline
  - neoteroi.cards
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/extra.css
  